# Generated by Django 5.0.4 on 2024-04-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_comments_offers_user_auctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='id_auction',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='id_auction',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_auctions',
            old_name='id_auction',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='user_auctions',
            old_name='id_user',
            new_name='user',
        ),
    ]
