# Generated by Django 5.0.4 on 2024-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_id_auction_comments_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('Electrodomésticos', 'Electrodomésticos'), ('Tecnología', 'Tecnología'), ('Ropa', 'Ropa'), ('Coleccionables', 'Coleccionables'), ('Juguetes', 'Juguetes'), ('Otros', 'Otros')], default='Otros', max_length=20),
        ),
    ]
